services:
  mcp-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: mcp-server
    volumes:
      - ./server:/app
      - ./data:/data
    ports:
      - "8000:8000"
    networks:
      - tfg-network

  ventas-agent:
    build:
      context: .
      dockerfile: agents/ventas_agent/Dockerfile
    container_name: ventas-agent
    volumes:
      - ./agents/ventas_agent:/app
      - ./server:/app/server
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - MCP_URL=http://mcp-server:8000
      - CALLBACK_URL=http://ventas-agent:8002/inbox
      - VENTAS_AGENT_ID
      - LLM_AGENT_ID
    depends_on:
      - mcp-server
    networks:
      - tfg-network

  llm-agent:
    build:
      context: .
      dockerfile: agents/llm_agent/Dockerfile
    container_name: llm-agent
    # No montamos volúmenes aquí para evitar ocultar el /app que construimos
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - MCP_URL=http://mcp-server:8000
      - CALLBACK_URL=http://llm-agent:8003/inbox
      - VENTAS_AGENT_ID
      - LLM_AGENT_ID
    depends_on:
      - mcp-server
      - ventas-agent
    networks:
      - tfg-network


networks:
  tfg-network:
    driver: bridge
