version: '3.8'

services:
  llm-client:
    build:
      context: ./client
    container_name: cliente-llm
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"  # Exponemos la API del cliente LLM
    depends_on:
      - mcp-server
    networks:
      - tfg-network

  mcp-server:
    build:
      context: ./server
    container_name: servidor-mcp
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - lake-storage
    networks:
      - tfg-network

  lake-storage:
    build:
      context: ./data
    container_name: almacenamiento-lake
    volumes:
      - ./data:/data
    networks:
      - tfg-network
    command: ["sleep", "infinity"]

networks:
  tfg-network:
    driver: bridge
